# Generated by Django 4.1.4 on 2023-02-28 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('home_phone_number', models.CharField(max_length=250)),
                ('inviter_name', models.CharField(blank=True, max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=250)),
                ('plate', models.CharField(max_length=250)),
                ('chasis_number', models.CharField(max_length=250)),
                ('color', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_information.carowner')),
            ],
        ),
    ]
